import React, { useCallback, useEffect, useRef, useState } from 'react';
import { UploadCloud, File, X, Check, Loader2, RotateCcw, Clock, Activity, Sparkles, FileDown, LayoutTemplate } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { parseFileToText, extractFileMetadata } from '../utils/fileParser.js';
import { executeSmartTask } from '../utils/aiClient.js';
import { useApp } from '../state/AppContext.jsx';
import { useGhostMacro } from '../state/GhostMacroContext.jsx';
import jsPDF from 'jspdf';

const RunMacro = () => {
  const location = useLocation();
  const locationAction = location.state?.action;
  const templateTitle = location.state?.templateTitle || null;
  const templateDescription = location.state?.templateDescription || null;
  const templateTask = location.state?.templateTask || null;
  const templateFileTypes = location.state?.templateFileTypes || null;
  const templateHint = location.state?.templateHint || null;
  const fromTemplate = location.state?.fromTemplate || false;
  const { addHistoryItem } = useApp();
  const { logAction, ghostModeEnabled, onFileOpened, evaluateFileForGhost, suggestedMacro } = useGhostMacro();
  const [task, setTask] = useState('');
  const [files, setFiles] = useState([]);
  const [status, setStatus] = useState('idle'); // idle, processing, complete
  const statusRef = useRef(status);
  const [progress, setProgress] = useState(0);
  const [currentStep, setCurrentStep] = useState(0);
  const [resultData, setResultData] = useState(null);
  const suggestedRunStep = suggestedMacro?.actionSequence?.find?.((a) => a?.type === 'RUN_MACRO') || null;

  const steps = [
    'Uploading file (local)...',
    'Parsing document...',
    'Processing content...',
    'Finalizing output...'
  ];

  useEffect(() => {
    if (templateTask) {
      // Template-specific detailed instruction takes priority
      setTask(templateTask);
    } else if (locationAction) {
      const actionMap = {
        summarize: 'Summarize this document',
        rewrite: 'Rewrite this document',
        format: 'Auto Format this content',
        cleanup: 'Clean up this document'
      };
      setTask(actionMap[locationAction] || locationAction);
    }
  }, [locationAction, templateTask]);

  useEffect(() => {
    statusRef.current = status;
  }, [status]);

  // Save output as PDF — defined inside component to access resultData state
  const handleSavePdf = () => {
    const rawText = resultData?.structuredOutput || resultData?.resultText || 'No result to save';

    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const marginLeft = 15;
    const marginRight = 15;
    const marginTop = 22;
    const marginBottom = 20;
    const usableWidth = pageWidth - marginLeft - marginRight;
    const RED = [220, 38, 38];   // red highlight color
    const DARK = [30, 30, 30];   // body text
    const MUTED = [100, 100, 100];

    // ── Header ──
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...RED);
    const title = task ? `JARVIS — ${task}` : 'JARVIS — Processed Result';
    doc.text(title, marginLeft, 13);
    doc.setDrawColor(...RED);
    doc.setLineWidth(0.4);
    doc.line(marginLeft, 16, pageWidth - marginRight, 16);

    let y = marginTop;
    let pageNum = 1;

    const checkPage = (needed = 6) => {
      if (y + needed > pageHeight - marginBottom) {
        addFooter(pageNum);
        doc.addPage();
        pageNum++;
        y = marginTop;
      }
    };

    const addFooter = (num) => {
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text(
        `Page ${num}  •  Generated by JARVIS`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' }
      );
      doc.setFontSize(10);
      doc.setTextColor(...DARK);
    };

    // Strip inline markdown for plain text rendering in PDF
    const stripInline = (s) => s
      .replace(/\*{1,2}([^*]+)\*{1,2}/g, '$1')
      .replace(/_{1,2}([^_]+)_{1,2}/g, '$1')
      .replace(/`([^`]+)`/g, '$1');

    const rawLines = rawText.split('\n');

    for (const line of rawLines) {
      const trimmed = line.trim();

      // Blank line
      if (trimmed === '') { y += 3; continue; }

      // Horizontal rule
      if (/^[-*_]{3,}$/.test(trimmed)) {
        checkPage(5);
        doc.setDrawColor(...RED);
        doc.setLineWidth(0.25);
        doc.line(marginLeft, y, pageWidth - marginRight, y);
        doc.setLineWidth(0.3);
        y += 4;
        continue;
      }

      // H1  # Heading
      const h1 = trimmed.match(/^#\s+(.+)/);
      if (h1) {
        checkPage(10);
        y += 3;
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...RED);
        const wrapped = doc.splitTextToSize(stripInline(h1[1]), usableWidth);
        doc.text(wrapped, marginLeft, y);
        y += wrapped.length * 6.5 + 1;
        // underline
        doc.setDrawColor(...RED);
        doc.setLineWidth(0.3);
        doc.line(marginLeft, y, pageWidth - marginRight, y);
        y += 3;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK);
        continue;
      }

      // H2  ## Heading
      const h2 = trimmed.match(/^##\s+(.+)/);
      if (h2) {
        checkPage(8);
        y += 2;
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...RED);
        const wrapped = doc.splitTextToSize(stripInline(h2[1]), usableWidth);
        doc.text(wrapped, marginLeft, y);
        y += wrapped.length * 6 + 2;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK);
        continue;
      }

      // H3+  ### Heading
      const h3 = trimmed.match(/^#{3,}\s+(.+)/);
      if (h3) {
        checkPage(7);
        y += 1.5;
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...RED);
        const wrapped = doc.splitTextToSize(stripInline(h3[1]), usableWidth);
        doc.text(wrapped, marginLeft, y);
        y += wrapped.length * 5.8 + 1.5;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK);
        continue;
      }

      // Blockquote  > text
      if (trimmed.startsWith('>')) {
        const bqText = stripInline(trimmed.replace(/^>\s*/, ''));
        checkPage(6);
        doc.setDrawColor(...RED);
        doc.setLineWidth(0.8);
        doc.line(marginLeft, y - 3.5, marginLeft, y + 1.5);
        doc.setLineWidth(0.3);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(...MUTED);
        const wrapped = doc.splitTextToSize(bqText, usableWidth - 4);
        doc.text(wrapped, marginLeft + 4, y);
        y += wrapped.length * 5.5 + 1;
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK);
        continue;
      }

      // Bullet  - item or * item
      const bullet = trimmed.match(/^[-*•]\s+(.+)/);
      if (bullet) {
        checkPage(6);
        // Red bullet arrow
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...RED);
        doc.setFontSize(11);
        doc.text('>', marginLeft, y);
        // Body text
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK);
        doc.setFontSize(10);
        const wrapped = doc.splitTextToSize(stripInline(bullet[1]), usableWidth - 6);
        doc.text(wrapped, marginLeft + 6, y);
        y += wrapped.length * 5.5 + 0.5;
        continue;
      }

      // Numbered list  1. item
      const numbered = trimmed.match(/^(\d+)\.\s+(.+)/);
      if (numbered) {
        checkPage(6);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...RED);
        doc.setFontSize(10);
        doc.text(`${numbered[1]}.`, marginLeft, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK);
        const wrapped = doc.splitTextToSize(stripInline(numbered[2]), usableWidth - 8);
        doc.text(wrapped, marginLeft + 8, y);
        y += wrapped.length * 5.5 + 0.5;
        continue;
      }

      // Key: Value line
      const kv = trimmed.match(/^([^:]{1,40}):\s+(.+)/);
      if (kv && !trimmed.startsWith('http')) {
        checkPage(6);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...MUTED);
        doc.text(`${kv[1]}:`, marginLeft, y);
        const labelW = doc.getTextWidth(`${kv[1]}: `) + 1;
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK);
        const wrapped = doc.splitTextToSize(stripInline(kv[2]), usableWidth - labelW);
        doc.text(wrapped, marginLeft + labelW, y);
        y += wrapped.length * 5.5 + 0.3;
        continue;
      }

      // Regular paragraph
      checkPage(6);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...DARK);
      const wrapped = doc.splitTextToSize(stripInline(trimmed), usableWidth);
      doc.text(wrapped, marginLeft, y);
      y += wrapped.length * 5.5 + 0.5;
    }

    addFooter(pageNum);

    const fileName = task
      ? `JARVIS_${task.slice(0, 30).replace(/[^a-z0-9]/gi, '_')}.pdf`
      : 'JARVIS_output.pdf';
    doc.save(fileName);
  };

  const handleProcess = useCallback(async ({ taskOverride, macroOverride, source } = {}) => {
    if (!task && (!files || files.length === 0)) {
      alert('Please provide a task description or upload at least one file.');
      return;
    }

    const startTime = Date.now();
    const action = macroOverride ?? locationAction;
    setStatus('processing');
    setResultData(null);
    setProgress(0);
    setCurrentStep(0);
    try {
      // Step 1: File parsing (immediate feedback) - ≤2s
      setCurrentStep(0);
      setProgress(10);

      let content = '';
      let fileMetadata;

      if (files && files.length > 0) {
        // Parse all files and combine their contents
        const parsed = [];
        let totalSize = 0;

        for (const f of files) {
          const text = await parseFileToText(f);
          parsed.push({ file: f, text });
          totalSize += f.size || 0;
        }

        content = parsed
          .map(({ file, text }, idx) => `--- File ${idx + 1}: ${file.name} ---\n${text}`)
          .join('\n\n');

        if (files.length === 1) {
          // Use rich metadata when a single file is provided
          fileMetadata = await extractFileMetadata(files[0]);
        } else {
          // Aggregate metadata for batch processing
          const sizeKb = (totalSize / 1024).toFixed(1);
          const wordCount = content.split(/\s+/).filter(Boolean).length;

          fileMetadata = {
            name: `${files.length} files (batch)`,
            type: 'MIXED',
            size: `${sizeKb} KB`,
            pages: Math.max(1, Math.round(wordCount / 300)),
            words: wordCount,
            isTextFile: true
          };
        }
      } else {
        // Text-only task
        content = task || '';
        fileMetadata = {
          name: 'Text Input',
          type: 'TXT',
          size: 'Unknown',
          pages: 1,
          words: content.split(/\s+/).length,
          isTextFile: true
        };
      }

      if (!content.trim()) {
        throw new Error('No readable content found in file');
      }

      // Step 2: Content sampling (fast) - ≤1s
      setCurrentStep(1);
      setProgress(30);

      // Step 3: Processing with GPT-quality engine
      setCurrentStep(2);
      setProgress(60);

      // Prepare user instruction (combine task description with any action context)
      const actionPrompts = {
        summarize: 'Summarize this document comprehensively',
        rewrite: 'Rewrite this document professionally',
        format: 'Auto-format this document for better readability',
        cleanup: 'Clean up and optimize this document',
      };
      let fullInstruction = taskOverride ?? task;
      if (!taskOverride && action && action !== 'custom') {
        fullInstruction = actionPrompts[action] || task;
      }

      logAction({
        type: 'RUN_MACRO',
        macro: action || undefined,
        task: fullInstruction,
        fileName: files?.[0]?.name || null,
        fileType: files?.[0]?.type || '',
        metadata: { task: fullInstruction, macro: action || null, source: source || 'manual' },
      });

      const processPromise = executeSmartTask({
        fileMetadata,
        parsedContent: content,
        userInstruction: fullInstruction
      });

      const timeoutPromise = new Promise((_, reject) =>
        setTimeout(() => reject(new Error('Processing timeout API took too long - please try again')), 45000) // 45s Timeout matching AI configuration
      );

      const result = await Promise.race([processPromise, timeoutPromise]);

      // Step 4: Finalize - ≤2s
      setCurrentStep(3);
      setProgress(100);

      console.log('Processing result:', result);
      setResultData(result);

      // Add to history with enhanced metadata
      addHistoryItem({
        task: fullInstruction,
        fileName: result.metadata.name,
        durationSeconds: Math.round(result.timeTaken * 100) / 100,
        quality: result.qualityScore / 100,
        resultText: result.structuredOutput,
        taskType: result.metadata.task || 'custom',
        analyzedPercentage: 100, // Always complete analysis now
        fileType: result.metadata.type,
        fileSize: result.metadata.size,
        wordCount: result.wordCount,
        pageEstimate: result.pageEstimate
      });

      // Complete with delay for UX
      setTimeout(() => setStatus('complete'), 300);
    } catch (err) {
      console.error('Processing error:', err);
      const errorResult = {
        taskType: 'error',
        resultText: `Processing failed: ${err.message}. Please try again or check your file.`,
        metrics: {
          qualityScore: 0,
          timeTaken: (Date.now() - startTime) / 1000,
          analyzedPercentage: 0
        }
      };
      setResultData(errorResult);
      setStatus('complete');
    }
  }, [addHistoryItem, files, locationAction, logAction, task]);

  useEffect(() => {
    if (!ghostModeEnabled || !files || files.length === 0) return;
    // Matching + auto-execution is handled by the Ghost engine (sessions + confidence + patterns)
    const primary = files[0];
    if (!primary) return;
    void evaluateFileForGhost(primary, {
      OPEN_FILE: async () => { },
      RUN_MACRO: async (action) => {
        if (statusRef.current !== 'idle') return;
        await handleProcess({ taskOverride: action?.task, macroOverride: action?.macro, source: 'ghost' });
      },
      EXPORT: async () => { },
    });
  }, [files, ghostModeEnabled, evaluateFileForGhost, handleProcess]);

  useEffect(() => {
    if (!files || files.length === 0) return;
    const primary = files[0];
    if (!primary) return;
    onFileOpened(primary);
  }, [files, onFileOpened]);

  useEffect(() => {
    if (status === 'complete') {
      try {
        const ctx = new (window.AudioContext || window.webkitAudioContext)();
        const osc = ctx.createOscillator();
        const gain = ctx.createGain();
        osc.frequency.value = 720;
        gain.gain.setValueAtTime(0.08, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + 0.25);
        osc.connect(gain).connect(ctx.destination);
        osc.start();
        osc.stop(ctx.currentTime + 0.25);
      } catch {
        // ignore audio errors in non-browser environments
      }
    }
  }, [status]);

  const handleDrop = (e) => {
    e.preventDefault();
    const droppedFiles = Array.from(e.dataTransfer.files || []);
    if (droppedFiles.length > 0) setFiles(droppedFiles);
  };

  // (handleProcess is defined above as a memoized callback)

  // Renders markdown-style output with highlighted headings, bullets, bold, code, etc.
  const RenderedOutput = ({ text }) => {
    if (!text) return <span style={{ color: 'var(--text-muted)' }}>Processing completed successfully. Document analysis finished.</span>;

    const lines = text.split('\n');

    // Render inline markdown: **bold**, *italic*, `code`
    const renderInline = (str) => {
      const parts = [];
      const regex = /(`[^`]+`)|\*\*([^*]+)\*\*|\*([^*]+)\*|__([^_]+)__/g;
      let last = 0;
      let match;
      let key = 0;
      while ((match = regex.exec(str)) !== null) {
        if (match.index > last) parts.push(<span key={key++}>{str.slice(last, match.index)}</span>);
        if (match[1]) {
          // inline code
          parts.push(
            <code key={key++} style={{ background: 'rgba(239,68,68,0.12)', color: '#fca5a5', padding: '0.1rem 0.4rem', borderRadius: '4px', fontSize: '0.85em', fontFamily: 'var(--font-mono, monospace)' }}>
              {match[1].slice(1, -1)}
            </code>
          );
        } else if (match[2]) {
          // bold
          parts.push(<strong key={key++} style={{ color: '#e2e8f0', fontWeight: 700 }}>{match[2]}</strong>);
        } else if (match[3] || match[4]) {
          // italic
          parts.push(<em key={key++} style={{ color: '#fca5a5' }}>{match[3] || match[4]}</em>);
        }
        last = match.index + match[0].length;
      }
      if (last < str.length) parts.push(<span key={key++}>{str.slice(last)}</span>);
      return parts.length > 0 ? parts : str;
    };

    const elements = [];
    let i = 0;
    while (i < lines.length) {
      const line = lines[i];
      const trimmed = line.trim();

      // Blank line
      if (trimmed === '') {
        elements.push(<div key={i} style={{ height: '0.6rem' }} />);
        i++;
        continue;
      }

      // Horizontal rule
      if (/^[-*_]{3,}$/.test(trimmed)) {
        elements.push(<hr key={i} style={{ border: 'none', borderTop: '1px solid rgba(239,68,68,0.35)', margin: '0.75rem 0' }} />);
        i++;
        continue;
      }

      // H1
      const h1 = trimmed.match(/^#\s+(.+)/);
      if (h1) {
        elements.push(
          <div key={i} style={{ fontSize: '1.15rem', fontWeight: 800, color: '#ef4444', marginTop: '1.1rem', marginBottom: '0.3rem', letterSpacing: '0.01em', borderBottom: '1px solid rgba(239,68,68,0.3)', paddingBottom: '0.3rem' }}>
            {renderInline(h1[1])}
          </div>
        );
        i++; continue;
      }

      // H2
      const h2 = trimmed.match(/^##\s+(.+)/);
      if (h2) {
        elements.push(
          <div key={i} style={{ fontSize: '1.05rem', fontWeight: 700, color: '#f87171', marginTop: '0.9rem', marginBottom: '0.2rem' }}>
            {renderInline(h2[1])}
          </div>
        );
        i++; continue;
      }

      // H3 / H4+
      const h3 = trimmed.match(/^#{3,}\s+(.+)/);
      if (h3) {
        elements.push(
          <div key={i} style={{ fontSize: '0.97rem', fontWeight: 700, color: '#fca5a5', marginTop: '0.7rem', marginBottom: '0.15rem' }}>
            {renderInline(h3[1])}
          </div>
        );
        i++; continue;
      }

      // Blockquote
      if (trimmed.startsWith('>')) {
        const bqText = trimmed.replace(/^>\s*/, '');
        elements.push(
          <div key={i} style={{ borderLeft: '3px solid #ef4444', paddingLeft: '0.85rem', margin: '0.3rem 0', color: '#94a3b8', fontStyle: 'italic', fontSize: '0.92rem' }}>
            {renderInline(bqText)}
          </div>
        );
        i++; continue;
      }

      // Bullet list item (-, *, •)
      const bullet = trimmed.match(/^[-*•]\s+(.+)/);
      if (bullet) {
        elements.push(
          <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '0.55rem', margin: '0.25rem 0', paddingLeft: '0.25rem' }}>
            <span style={{ color: '#ef4444', fontWeight: 900, fontSize: '1rem', lineHeight: '1.55', flexShrink: 0 }}>▸</span>
            <span style={{ color: '#e2e8f0', lineHeight: 1.6, fontSize: '0.92rem' }}>{renderInline(bullet[1])}</span>
          </div>
        );
        i++; continue;
      }

      // Numbered list item
      const numbered = trimmed.match(/^(\d+)\.\s+(.+)/);
      if (numbered) {
        elements.push(
          <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '0.6rem', margin: '0.25rem 0', paddingLeft: '0.25rem' }}>
            <span style={{ color: '#ef4444', fontWeight: 700, fontSize: '0.85rem', minWidth: '1.4rem', lineHeight: '1.6', flexShrink: 0 }}>{numbered[1]}.</span>
            <span style={{ color: '#e2e8f0', lineHeight: 1.6, fontSize: '0.92rem' }}>{renderInline(numbered[2])}</span>
          </div>
        );
        i++; continue;
      }

      // Key-value / label: value line (e.g. "Date: 2024-01-01")
      const kv = trimmed.match(/^([^:]{1,40}):\s+(.+)/);
      if (kv && !trimmed.startsWith('http')) {
        elements.push(
          <div key={i} style={{ display: 'flex', gap: '0.5rem', margin: '0.2rem 0', fontSize: '0.9rem', lineHeight: 1.6 }}>
            <span style={{ color: '#94a3b8', fontWeight: 600, flexShrink: 0 }}>{kv[1]}:</span>
            <span style={{ color: '#e2e8f0' }}>{renderInline(kv[2])}</span>
          </div>
        );
        i++; continue;
      }

      // Regular paragraph line
      elements.push(
        <div key={i} style={{ color: '#cbd5e1', lineHeight: 1.7, fontSize: '0.92rem', margin: '0.15rem 0' }}>
          {renderInline(trimmed)}
        </div>
      );
      i++;
    }

    return <div style={{ display: 'flex', flexDirection: 'column' }}>{elements}</div>;
  };

  const ResultView = () => {
    console.log('ResultView rendering with resultData:', resultData);
    const hasFiles = files && files.length > 0;
    const fileLabel = hasFiles
      ? (files.length === 1 ? files[0].name : `${files.length} files (batch)`)
      : 'Text Input';

    return (
      <div className="animate-fade-in">
        <div className="glass-panel" style={{ padding: '2rem', marginBottom: '2rem', borderLeft: '4px solid var(--accent-secondary)' }}>
          <div className="flex-between" style={{ alignItems: 'flex-start', marginBottom: '1.2rem' }}>
            <div>
              <h2 style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <div style={{ background: 'rgba(16, 185, 129, 0.2)', padding: '0.5rem', borderRadius: '50%' }}>
                  <Check size={24} color="var(--accent-secondary)" />
                </div>
                Processing Complete!
              </h2>
              <div style={{ marginTop: '0.35rem', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                Task: {task || `${resultData?.taskType || 'Custom'} Processing`} <br />
                File: {fileLabel}
              </div>
            </div>
            <div style={{ textAlign: 'right', display: 'flex', alignItems: 'center', gap: '1rem' }}>
              <div style={{ width: '62px', height: '62px', borderRadius: '50%', background: `conic-gradient(var(--accent-secondary) 0% ${resultData?.qualityScore || 98}%, rgba(255,255,255,0.08) ${resultData?.qualityScore || 98}% 100%)`, display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 0 0 1px rgba(255,255,255,0.08)' }}>
                <div style={{ width: '48px', height: '48px', borderRadius: '50%', background: '#0f1117', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-primary)', fontWeight: 700 }}>
                  {resultData?.qualityScore || 98}%
                </div>
              </div>
              <div>
                <div className="badge accent" style={{ marginBottom: '0.4rem' }}>
                  <Clock size={14} /> {resultData?.timeTaken ? `${resultData.timeTaken.toFixed(1)}s` : '4.2s'}
                </div>
                <div className="badge success">Quality score</div>
              </div>
            </div>
          </div>

          <div className="mono-box">
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.85rem', alignItems: 'center' }}>
              <h3 style={{ margin: 0, color: 'var(--accent-primary)', fontSize: '1rem' }}>Result</h3>
              <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                <span className="muted" style={{ fontSize: '0.85rem' }}>
                  {resultData?.wordCount || 0} words • ~{resultData?.pageEstimate || 1} pages
                </span>
                <div className="badge accent" style={{ fontSize: '0.8rem' }}>
                  Quality: {resultData?.qualityScore || 95}%
                </div>
              </div>
            </div>
            <div style={{ padding: '0.25rem 0' }}>
              <RenderedOutput text={resultData?.structuredOutput} />
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '0.8rem', flexWrap: 'wrap' }}>
          <button
            className="btn btn-primary"
            onClick={handleSavePdf}
          >
            <FileDown size={18} /> Save as PDF
          </button>
          <button
            className="btn btn-secondary"
            onClick={() => { setStatus('idle'); setFiles([]); setTask(''); setCurrentStep(0); setProgress(0); setResultData(null); }}
          >
            <RotateCcw size={18} /> Process Another
          </button>
          <button className="btn btn-secondary" style={{ border: 'none' }}>
            View in History
          </button>
        </div>
      </div>
    );
  };

  return (
    <div className="page-container">
      {status !== 'complete' && (
        <>
          <header style={{ marginBottom: fromTemplate ? '1rem' : '1.5rem' }}>
            <h1 style={{ fontSize: '2rem' }}>{fromTemplate ? 'Apply Template' : 'Run Macro'}</h1>
            <p className="section-subtitle">
              {fromTemplate
                ? 'Your template is pre-configured and ready — just upload your file and run.'
                : 'Describe your goal, attach files, and let JARVIS handle the rest.'}
            </p>
          </header>

          {fromTemplate && templateTitle && (
            <div
              className="glass-panel"
              style={{
                padding: '1rem 1.25rem',
                marginBottom: '1.5rem',
                borderLeft: '4px solid var(--accent-primary)',
                display: 'flex',
                alignItems: 'center',
                gap: '0.9rem',
                background: 'rgba(108,110,255,0.07)',
              }}
            >
              <div style={{ padding: '0.55rem', background: 'rgba(108,110,255,0.15)', borderRadius: '8px', flexShrink: 0 }}>
                <LayoutTemplate size={20} color="var(--accent-primary)" />
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: 700, fontSize: '1rem', marginBottom: '0.15rem' }}>{templateTitle}</div>
                {templateDescription && (
                  <div className="muted" style={{ fontSize: '0.88rem' }}>{templateDescription}</div>
                )}
              </div>
              {templateFileTypes && (
                <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontFamily: 'var(--font-mono, monospace)', background: 'rgba(255,255,255,0.05)', padding: '0.3rem 0.7rem', borderRadius: '6px', flexShrink: 0 }}>
                  📎 {templateFileTypes}
                </div>
              )}
            </div>
          )}

          <div className="glass-panel glow-border" style={{ padding: '2rem' }}>
            <div className="card-grid-2" style={{ alignItems: 'stretch' }}>
              <div className="flex-col" style={{ gap: '1.25rem' }}>
                <div>
                  <label style={{ display: 'block', marginBottom: '0.6rem', fontWeight: 600 }}>What should JARVIS do?</label>
                  <textarea
                    className="input-field"
                    rows={3}
                    placeholder="Describe what you want to do… (e.g., “Summarize and highlight action items”)"
                    value={task}
                    onChange={(e) => setTask(e.target.value)}
                  />
                </div>
              </div>

              <div
                className="glass-panel"
                style={{
                  padding: '2rem',
                  border: '1px dashed var(--border-color)',
                  textAlign: 'center',
                  cursor: 'pointer'
                }}
                onDragOver={(e) => e.preventDefault()}
                onDrop={handleDrop}
                onClick={() => document.getElementById('file-upload').click()}
              >
                <input
                  type="file"
                  multiple
                  id="file-upload"
                  style={{ display: 'none' }}
                  onChange={(e) => setFiles(Array.from(e.target.files || []))}
                />
                {files && files.length > 0 ? (
                  <div className="flex-col" style={{ alignItems: 'center' }}>
                    <File size={46} color="var(--accent-primary)" />
                    <div style={{ fontSize: '1.05rem', fontWeight: 600 }}>
                      {files.length === 1 ? files[0].name : `${files.length} files selected`}
                    </div>
                    <div className="muted">
                      {`${(files.reduce((sum, f) => sum + (f.size || 0), 0) / 1024).toFixed(1)} KB total`}
                    </div>
                    <button
                      className="btn btn-ghost"
                      style={{ color: '#ef4444' }}
                      onClick={(e) => { e.stopPropagation(); setFiles([]); }}
                    >
                      <X size={16} /> Remove
                    </button>
                  </div>
                ) : (
                  <>
                    <div style={{ width: '70px', height: '70px', borderRadius: '16px', background: 'rgba(108,110,255,0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1rem' }}>
                      <UploadCloud size={32} color="var(--text-secondary)" />
                    </div>
                    <div style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '0.35rem' }}>Drag &amp; drop or click to upload</div>
                    <div className="muted">
                      {templateHint
                        ? templateHint
                        : 'Supported: pdf, docx, xlsx, pptx, csv, txt, json'}
                    </div>
                    {templateFileTypes && (
                      <div style={{ marginTop: '0.5rem', fontSize: '0.78rem', color: 'var(--accent-primary)', fontFamily: 'var(--font-mono, monospace)' }}>
                        {templateFileTypes}
                      </div>
                    )}
                  </>
                )}
              </div>
            </div>

            {status === 'idle' && suggestedMacro && files && files.length > 0 && (
              <div
                className="glass-panel"
                style={{
                  padding: '1rem',
                  marginTop: '1.25rem',
                  borderLeft: '3px solid var(--accent-primary)',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  gap: '0.9rem',
                }}
              >
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.45rem', marginBottom: '0.2rem' }}>
                    <Sparkles size={16} color="var(--accent-primary)" />
                    <span style={{ fontWeight: 700 }}>Ghost suggestion</span>
                    <span className="badge accent" style={{ fontSize: '0.75rem' }}>
                      {suggestedMacro.confidenceScore}% confidence
                    </span>
                  </div>
                  <div className="muted" style={{ fontSize: '0.9rem' }}>
                    {(suggestedMacro.actionSequence || []).map((a) => a.type).join(' → ')} · Pattern:{' '}
                    <code>{suggestedMacro.fileNamePattern}</code>
                  </div>
                  {!ghostModeEnabled && (
                    <div className="muted" style={{ fontSize: '0.82rem', marginTop: '0.25rem' }}>
                      Ghost Mode is off, so this won’t auto-run.
                    </div>
                  )}
                </div>
                <div style={{ display: 'flex', gap: '0.5rem', flexShrink: 0 }}>
                  <button
                    type="button"
                    className="btn btn-primary"
                    disabled={status !== 'idle'}
                    onClick={() => {
                      void handleProcess({
                        taskOverride: suggestedRunStep?.task,
                        macroOverride: suggestedRunStep?.macro,
                        source: 'ghost_suggestion',
                      });
                    }}
                    style={{ padding: '0.45rem 0.9rem', fontSize: '0.85rem' }}
                  >
                    Run suggested workflow
                  </button>
                </div>
              </div>
            )}

            {status === 'idle' ? (
              <button
                className="btn btn-primary"
                style={{ width: '100%', marginTop: '1.5rem' }}
                disabled={(!files || files.length === 0) && !task}
                onClick={handleProcess}
              >
                Start Processing
              </button>
            ) : (
              <div className="glass-panel" style={{ padding: '1.25rem', marginTop: '1.5rem' }}>
                <div className="flex-between" style={{ marginBottom: '0.8rem' }}>
                  <span className="flex-row" style={{ gap: '0.5rem' }}>
                    <Loader2 className="spin" size={18} color="var(--accent-primary)" style={{ animation: 'spin 1.5s linear infinite' }} />
                    {steps[currentStep] || 'Processing...'}
                  </span>
                  <span>{Math.round(progress)}%</span>
                </div>
                <div style={{ width: '100%', height: '8px', background: 'rgba(255,255,255,0.08)', borderRadius: '999px', overflow: 'hidden' }}>
                  <div style={{
                    width: `${progress}%`,
                    height: '100%',
                    background: 'linear-gradient(90deg, var(--accent-primary), #9f9bff)',
                    transition: 'width 0.25s ease'
                  }} />
                </div>
                <div className="flex-between" style={{ marginTop: '0.75rem', color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                  <span>Uploading ✓ • Parsing ✓ • Processing ⏳ • Finalizing …</span>
                  <span className="badge accent" style={{ gap: '0.4rem' }}><Activity size={14} /> Thinking</span>
                </div>
                <div className="flex-row" style={{ marginTop: '0.8rem', gap: '0.6rem', flexWrap: 'wrap' }}>
                  {steps.map((label, idx) => {
                    const state = idx < currentStep ? 'done' : idx === currentStep ? 'active' : 'pending';
                    return (
                      <div
                        key={label}
                        className="badge"
                        style={{
                          borderColor: state === 'active' ? 'rgba(108,110,255,0.5)' : 'var(--border-color)',
                          color: state === 'done' ? 'var(--accent-secondary)' : state === 'active' ? 'var(--accent-primary)' : 'var(--text-muted)'
                        }}
                      >
                        {state === 'done' ? '✓' : state === 'active' ? '•' : '…'} {label.replace('...', '')}
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        </>
      )}

      {status === 'complete' && resultData?.taskType === 'error' && (
        <div className="glass-panel" style={{ padding: '2rem', marginBottom: '2rem', borderLeft: '4px solid #ef4444' }}>
          <div className="flex-between" style={{ alignItems: 'flex-start', marginBottom: '1.2rem' }}>
            <div>
              <h2 style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', color: '#ef4444' }}>
                <div style={{ background: 'rgba(239, 68, 68, 0.2)', padding: '0.5rem', borderRadius: '50%' }}>
                  <X size={24} color="#ef4444" />
                </div>
                Processing Failed
              </h2>
              <div style={{ marginTop: '0.35rem', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                {resultData?.resultText}
              </div>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '0.8rem', flexWrap: 'wrap' }}>
            <button
              className="btn btn-secondary"
              onClick={() => { setStatus('idle'); setFiles([]); setTask(''); setCurrentStep(0); setProgress(0); setResultData(null); }}
            >
              <RotateCcw size={18} /> Try Again
            </button>
          </div>
        </div>
      )}

      {status === 'complete' && resultData?.taskType !== 'error' && <ResultView />}
    </div>
  );
};

export default RunMacro;
